src/app/app.module.ts
src/app/bricks.ts
src/app/bricks/bricks.module.ts
src/app/bricks/comp/comp_single_choice.component.ts
src/app/bricks/comp/comp_text.component.ts
src/app/bricks/live.component.scss
src/app/bricks/live.component.ts

Add Text component.
Rename MultipleChoice to SingleChoice

Modify CSS for responsiveness.

---

src/app/app.component.ts

It`s an internal bug of Dragula library. I added fix which will prevent scroll during Drag event of Dragula.

#93 Fix for IOS11 drag issue with dragula

---

src/app/play/brick/live.component.html

#85 Change next button to go to next question

---

src/app/play/brick/comp/comp_text_highlighting.component.ts
src/app/play/brick/review.component.html

#86 Make live review horizontal

---

src/app/play/brick/comp/comp_sort.component.scss
src/app/play/brick/comp/comp_sort.component.ts
src/app/play/brick/live.component.scss

#199 SortComponent. Create file for his styles

---

src/app/play/brick/comp/comp_single_choice.component.ts

#182 Not showing empty reveals in single choice component.

#182 SingleChoiceComponent. Hide reveals if empty and set as innerHTML

---

src/app/play/brick/review.component.html

#195 ReviewComponent. On click next button go next question

---

src/app/build/brick/introduction.component.ts
src/app/play/brick/introduction.component.ts

#220 IntroductionComponent. /intro no autopogress

---

src/app/build/brick/brick.routing.ts
src/app/build/brick/provisional_score.component.html
src/app/build/brick/provisional_score.component.ts
src/app/play/brick/brick.routing.ts
src/app/play/brick/provisional_score.component.html
src/app/play/brick/provisional_score.component.ts

#215 BrickRouting. /summary to /synthesis

---

src/app/play/brick/comp/comp_text_highlighting.component.ts

#227 TextHighlightingComponent. Set innerHTML words.

---

src/app/play/brick/live.component.html

#218 LiveComponent. Remove done icon

---

app.json

#200 Connect to dev firestore

---

src/styles.scss

#219 #209 Fix styling for Phones

#209 MatStepper fix styling

---

src/app/build/brick/comp/comp_multiple_choice.component.ts
src/app/play/brick/comp/comp_multiple_choice.component.ts

#66 MultipleChoiceComponent. Fix sums. Wrong answer -5, correct one +5

---

src/app/play/brick/summary.component.html
src/app/play/brick/summary.component.scss

#216 SummaryComponent. MatCardContent justify center

---

src/app/play/brick/live.component.html
src/app/play/brick/live.component.scss
src/app/play/brick/live.component.ts
src/styles.scss

209 mat stepper improvements

---

src/app/play/brick/summary.component.html

#244 SummaryComponent. Fix card title content

---

src/app/play/brick/comp/comp_poem.component.ts
src/app/play/brick/live.component.scss

#241 PoemComponent. Text justify center

---

src/app/play/brick/comp/comp_arrow.component.ts

#214 ArrowQuestionComponent. Fix left column

---

src/app/play/brick/comp/comp_order.component.ts

#242 Share style arrow and order for drag and drop box

#242 OrderComponent. Set dashed border

---

src/app/play/brick/comp/comp_text_dropdowns.component.ts

#250 TextDropdownsComponent. Randomize choices with shuffle

---

src/app/play/brick/comp/comp_arrow.component.ts
src/app/play/brick/live.component.scss

Reverts Scholar-6/learning-fortress-frontend#267

Revert "removed touch-action:none"

---

src/app/play/brick/comp/comp_text_dropdowns.component.ts

#277 TextDropdownsComponent. Choices as [innerHTML]

---

src/app/play/brick/comp/comp_multiple_choice.component.ts

#278 Show crosses only for selected choices.

#278 MultipleChoiceComponent. Fix crosses in review phrase

---

src/app/play/brick/brick.service.ts
src/app/play/brick/introduction.component.ts
src/app/schema.ts

#271 Sanitize introduction prep only once. Update brick schema.

#271 IntroductionComponent. Sanitizering prep once
